### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by ein-erin** [Navatusein/Silero-TTS-Service#1]
Очень хочу поблагодарить. Этот проект появился на гитхабе удивительно вовремя, я как раз ломал голову, пытаясь каким-нибудь образом прикрутить Silero к Home Assistant (и у меня ничего не получалось).

Единственное, что было не очевидно, и о чем хочется упомянуть чтобы сэкономить кому-нибудь время: 
подключение к Rhasspy настраивается в модуле MaryTTS.

![2022-12-21_12-21](https://user-images.githubusercontent.com/12344392/208827690-95c4d5af-48a6-4b5e-8e57-f9b4f57c0b56.png)

**Comment by Navatusein** [comment]
Рад что мой проект пригодился. По поводу неочевидности, я просто не успел расписать документацию. Времени особо не было, так как сессия началась.

**Comment by Navatusein** [comment]
> Очень хочу поблагодарить. Этот проект появился на гитхабе удивительно вовремя, я как раз ломал голову, пытаясь каким-нибудь образом прикрутить Silero к Home Assistant (и у меня ничего не получалось).
> 
> Единственное, что было не очевидно, и о чем хочется упомянуть чтобы сэкономить кому-нибудь время: подключение к Rhasspy настраивается в модуле MaryTTS.
> 
> ![2022-12-21_12-21](https://user-images.githubusercontent.com/12344392/208827690-95c4d5af-48a6-4b5e-8e57-f9b4f57c0b56.png)

Я дописал документацию. Обратите внимание на функциональные возможности сервера.

**Comment by ein-erin** [comment]
Круто! Сейчас почитаю про SSML, звучит очень интересно. Я знал только как ударение поставить.
