### ISSUE TITLE
Выводить данные  о скачивание и установки зависимостей в лог докера

### ISSUE THREAD

**Issue by Omirax** [Navatusein/Silero-TTS-Service#11]
Здравствуйте!

Идея уменьшить образ - великолепна!
Но было бы здорово ендюзеру  дать визуальные данные, что идет процесс скачивание и установка зависимостей.
Сейчас просто  
```
INFO [2022-12-25 12:35:14,343] Starting updating
INFO [2022-12-25 12:35:15,321] Update requirements
Collecting torch==1.13.1
  Downloading torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl (887.5 MB)
```
и висит уже некоторое время.
То есть малоинформативно.

Дополнено: 
Я имею ввиду отображать % того, что скачивается.
Но, кроме того, как мне кажется, философия докера - работа из коробки -  немного нарушается. ИМХО

**Comment by Navatusein** [comment]
> Здравствуйте!
> 
> Идея уменьшить образ - великолепна! Но было бы здорово ендюзеру дать визуальные данные, что идет процесс скачивание и установка зависимостей. Сейчас просто
> 
> ```
> INFO [2022-12-25 12:35:14,343] Starting updating
> INFO [2022-12-25 12:35:15,321] Update requirements
> Collecting torch==1.13.1
>   Downloading torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl (887.5 MB)
> ```
> 
> и висит уже некоторое время. То есть малоинформативно.
> 
> Дополнено: Я имею ввиду отображать % того, что скачивается. Но, кроме того, как мне кажется, философия докера - работа из коробки - немного нарушается. ИМХО

По поводу красивого отображения, я подумаю как это сделать. 
А по поводу работы из коробки. Оно же всё само делает. Просто вес образа в 7.8 Гб такая себе идея. И каждый раз при мелких фиксах его перекачивать, тоже такое себе. По этому и была внедрена система авто обновления. И мне теперь не нужно при мелких фиксах пересобирать образ и заново его выкладывать. Да и зависимости устанавливаються только при первом запуске, ну или если я их обновлю.

**Comment by Omirax** [comment]
А как именно будет инициироваться обновление и кем?
Если автообновление, то, как правило, должна быть опция, которая ее отключает.
А как инициировать ручное? Это уже надо front минимальный... 
Опять же ИМХО

**Comment by Omirax** [comment]
Сегодня решил изменить SAMPLE_RATE
Ребилд контейнера привел к полному перекачиванию и установок зависимостей.

Это очень не удобно.

**Comment by Navatusein** [comment]
> Сегодня решил изменить SAMPLE_RATE Ребилд контейнера привел к полному перекачиванию и установок зависимостей.
> 
> Это очень не удобно.

У меня опять выключали свет на 2 суток. Ок, я верну установку зависимостей и на уберу систему авто обновления. Но вес образа все равно проблема, которую нужно решать.

**Comment by Navatusein** [comment]
Всё вернул как было.

**Comment by Omirax** [comment]
Ну я бы предложил в environment добавить:
`AUTO_UPDATE = true | false`

И на основе этого строить логику сейчас. А в дальнейшем можно через HA  сделать вызов обновления зависимостей, дергая ссылку.

**Comment by Navatusein** [comment]
Я все равно хочу сделать этот сервис как аддон к Home Assistant.

**Comment by Omirax** [comment]
>Я все равно хочу сделать этот сервис как аддон к Home Assistant.

Идея отличная! 
Главное, с возможностью ручной установки в custom_components.

**Comment by Navatusein** [comment]
> > Я все равно хочу сделать этот сервис как аддон к Home Assistant.
> 
> Идея отличная! Главное, с возможностью ручной установки в custom_components.

Это будет не компонент а аддон. К сожалению как компонент у меня не получается сделать. PyTorch на отрез не хочет устанавливаться средствами Home Assistant. Так что буду упаковывать в дополнения.
![image](https://user-images.githubusercontent.com/53920406/209685788-4e69e532-ea07-4dbc-928e-721e99fd021c.png)

**Comment by Omirax** [comment]
Ну, к примеру, очень много кто никаких аддонов не использует. Я вообще все в отдельных докер-контейнерах держу. 
Поэтому, если не сложно, оставьте альтернативы.

Пробовали через manifest.json?

**Comment by Navatusein** [comment]
> Ну, к примеру, очень много кто никаких аддонов не использует. Я вообще все в отдельных докер-контейнерах держу. Поэтому, если не сложно, оставьте альтернативы.
> 
> Пробовали через manifest.json?

Так аддоны и запускаться в отдельных докер контейнерах. Просто ими можно удобно управлять и конфигурировать. Плюс есть уже нормальная система обновлений. В любом случаи я оставлю это сервис и в виде отдельного контейнера. А по поводу manifest.json. Вся проблема в том что  Home Assistant по не понятной для меня причины, не видит PyTorch.

``` 
2022-12-27 18:40:56.161 ERROR (SyncWorker_0) [homeassistant.util.package] Unable to install package torch==1.13.1: ERROR: Could not find a version that satisfies the requirement torch==1.13.1 (from versions: none)
ERROR: No matching distribution found for torch==1.13.1
[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
```

**Comment by Omirax** [comment]
Я в курсе про контейнеры. :) 

>Could not find a version that satisfies the requirement torch 

Было такое. Но у меня проблема была в разрядности Python. 
PyTorch же только на 64 можно, если мне не изменяет память. Да и то, не все версии.

**Comment by Navatusein** [comment]
> Я в курсе про контейнеры. :)
> 
> > Could not find a version that satisfies the requirement torch
> 
> Было такое. Но у меня проблема была в разрядности Python. PyTorch же только на 64 можно, если мне не изменяет память. Да и то, не все версии.

В любом случаи, решать эту проблему у меня желания нету не какого. Обходной путь был найден и он работает нормально.
