### ISSUE TITLE
HA assist

### ISSUE THREAD

**Issue by Omirax** [Navatusein/Silero-TTS-Service#19]
Приветствую!

А не замахнуться ли на что-то более глобальное и упрощающее жизнь и  убрать прослойку в виде Rhasspy Assistant?
К примеру есть https://www.home-assistant.io/docs/assist/ или REST API от HA...

Как думаете?

**Comment by Navatusein** [comment]
Я думал о том чтобы сделать что-то похожие на своего голосового ассистента. Но такая работёнка требует время которого сейчас мало.

**Comment by Navatusein** [comment]
Но я не отрицаю что всё таки займусь рано или поздно.

**Comment by Omirax** [comment]
Я готов помочь по мере сил, если что-то потребуется.  
Если взяться спокойно, не спеша - то думаю это будет "лучшее предложение на рынке" голосовых ассистентов для НА.

Например, могу заняться железом.

**Comment by NW15D** [comment]
Rhasspy и не нужен, ассистент собирается в полпинка. Whisper + LL< (любая нейросетка от openapi, яндекса до локальных). Зависит от задач.

![Screenshot from 2024-02-05 17-20-07](https://github.com/Navatusein/Silero-TTS-Service/assets/1011406/cdc5ccbb-9883-4f28-9bc7-9ba11679ec70)
