### ISSUE TITLE
Голос valeria не работает на ru языке

### ISSUE THREAD

**Issue by Spirituss** [Navatusein/Silero-TTS-Service#21]
Голос Valeria указан в списке доступных в боте @silero_voice_bot, но при попытке вызова TTS получаю такую ошибку:
```
ERROR Invalid speaker: speaker valeria not supported by this language
```

**Comment by Navatusein** [comment]
К сожалению, создатели бота уже давно не обновляли свои обще доступные модели. Их бот, это демонстратор возможностей, чтобы использовать его модели нужно платить.

|    Язык    | Код языка | Поддерживаемые голоса                              |
|:----------:|:---------:|:---------------------------------------------------|
|  Русский   |   `ru`    | `aidar` `baya` `kseniya` `xenia` `eugene` `random` |
| Українська |   `uk`    | `mykyta` `random`                                  |

Вот все голоса которые поддерживаются.
