### ISSUE TITLE
Start with CUDA 

### ISSUE THREAD

**Issue by NW15D** [Navatusein/Silero-TTS-Service#22]
Добрый день для запуска с CUDA достаточно использовать ранее установленный  pytorch с CUdA? или логика в коде не позволит его юзать ?

**Comment by NW15D** [comment]
just change in tts.py torch.device= cpu -> torch.device= ("cuda",0)

**Comment by Navatusein** [comment]
Я не уверен, что оно так легко запуститься. В докер образе версия py torch без поддержки cuda.

**Comment by Navatusein** [comment]
Как будет минутка попробую на cuda запустить.

**Comment by NW15D** [comment]
Отлично работает все с CUDA ) при установке (без докера),  вот расширить голоса до multi \ en пока не удается , ну и не все цифры говорит, т.е. на 2024 можно не расчитывать.
![image](https://github.com/Navatusein/Silero-TTS-Service/assets/1011406/721e779a-3dcf-4d89-b280-9363c66e4ad6)

**Comment by NW15D** [comment]
> Я не уверен, что оно так легко запуститься. В докер образе версия py torch без поддержки cuda.

Для docker образа c CUDA надо за базу брать какуй нить cublas  сборку типа этого 

https://github.com/mudler/LocalAI/blob/master/Dockerfile  (там где Cublas коммент)

**Comment by Navatusein** [comment]
У меня с СUDA вообще не получилось запустить. Не знаю чего, да и разбираться пока желания нет.

**Comment by NW15D** [comment]
> У меня с СUDA вообще не получилось запустить. Не знаю чего, да и разбираться пока желания нет.

Надо Nvidia GPU , драйвера,  и 

requirements_cuda.txt
torch==2.1.2 --index-url https://download.pytorch.org/whl/cu118
#torch==1.13.1
uvicorn~=0.20.0
fastapi~=0.88.0
pydantic~=1.10.2
num2words~=0.5.12
numpy~=1.23.5
pymorphy2~=0.9.1
pymorphy2-dicts-uk~=2.4.1.1.1460299261
transliterate~=1.10.2
requests~=2.28.1
