### ISSUE TITLE
Проблема со стартом образа

### ISSUE THREAD

**Issue by Omirax** [Navatusein/Silero-TTS-Service#27]
~$ docker compose up -d
Creating smarthome_silero-tts-service_run ... done
ERROR: 132

Железо:
Operating System: Ubuntu 23.04
Kernel: Linux 6.2.0-39-generic
Architecture: x86-64
Hardware Vendor: Gigabyte Technology Co., Ltd.
Hardware Model: J1900N-D3V

**Comment by Omirax** [comment]
Я так понял, нужен torch без AVX, а это только из исходников собирать 
UPD
Я собрал torch для процессоров без AVX. И оно даже работает. К сожалению директории от CUDA надо подкидывать ручками, хотя они и не используются. К сожалению каким флагом при cmake компиляции отключить CUDA во втором torch я не нашел.

**Comment by oscrey** [comment]
>  Я так понял, нужен torch без AVX, а это только из исходников собирать UPD Я собрал torch для процессоров без AVX. И оно даже работает. К сожалению директории от CUDA надо подкидывать ручками, хотя они и не используются. К сожалению каким флагом при cmake компиляции отключить CUDA во втором torch я не нашел.

у меня таже проблема на запускается на  intel cpu :(
буду очень благодарен если подскажите как собрать  torch без AVX
может линк какойто есть.

**Comment by Omirax** [comment]
Примерно вот так:

```
wget https://github.com/pytorch/pytorch/releases/download/v1.11.0/pytorch-v1.11.0.tar.gz && \
tar -xvzf pytorch-v1.11.0.tar.gz && rm pytorch-v1.11.0.tar.gz && \
cd pytorch-v1.11.0 && mkdir build && cd build && \
cmake -D CMAKE_BUILD_TYPE=Release \
      -D USE_AVX=OFF \
      -D USE_NNPACK=OFF \
      -D USE_MKLDNN=OFF \
      -D C_HAS_AVX_2=OFF \
      -D C_HAS_AVX2_2=OFF \
      -D CXX_HAS_AVX_2=OFF \
      -D CXX_HAS_AVX2_2=OFF \
      -D CAFFE2_COMPILER_SUPPORTS_AVX512_EXTENSIONS=OFF \
      .. && \
make -j4 && \
sudo make install
```
Только pytorch последний, 2-й. Я скомпилил, то есть - работает.

**Comment by oscrey** [comment]
> Примерно вот так:

Спасибо большое буду пробовать

Вы еще писали что нужно

>  директории от CUDA надо подкидывать ручками

можете уточнить откуда ее (CUDA) брать и в какой каталог подкидывать

**Comment by Omirax** [comment]
Из каталога pytorch. 
При инсталляции увидите, ругаться будет на отсутствие файлов.

**Comment by oscrey** [comment]
в итоге у меня получилось проще решить проблему
просто пересобрал на своем железе докер-контейнер из  исходников что на гите автора
и о чудо - он стартанул :)
