### ISSUE TITLE
Could not initialize NNPACK! 

### ISSUE THREAD

**Issue by Omirax** [Navatusein/Silero-TTS-Service#3]
Приветствую!
При запуске контейнера получаем  `[W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware ` 

Предположение:
USE_NNPACK=0 ?
Может стоит вынести в environment?

**Comment by Navatusein** [comment]
> Приветствую! При запуске контейнера получаем `[W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware `
> 
> Предположение: USE_NNPACK=0 ? Может стоит вынести в environment?

Первый раз слышу о такой проблеме. По быстрому поиску USE_NNPACK=0  нужно добавлять при сборке библиотеки pyTorch. В моём случаи устанавливается уже собранная библиотека с pip.

**Comment by Omirax** [comment]
Не критично, можно закрывать, я думаю.

**Comment by artenax** [comment]
У меня такое сообщение на pytorch 1.11.0+cpu из-за того, что проц не поддерживает AVX.
