### ISSUE TITLE
Согласование склонений

### ISSUE THREAD

**Issue by ein-erin** [Navatusein/Silero-TTS-Service#4]
Привет. 

Нашел такую проблему. Склонение чисел не всегда согласуется со следующими после них существительными.

```
1 <d>минута</d>      один минута
2 <d>минута</d>      два минута
3 <d>минута</d>      три минуты
41 <d>минута</d>    сорок один минута
44 <d>минута</d>    сорок четыре минуты
```

**Comment by Navatusein** [comment]
> Привет.
> 
> Нашел такую проблему. Склонение чисел не всегда согласуется со следующими после них существительными.
> 
> ```
> 1 <d>минута</d>      один минута
> 2 <d>минута</d>      два минута
> 3 <d>минута</d>      три минуты
> 41 <d>минута</d>    сорок один минута
> 44 <d>минута</d>    сорок четыре минуты
> ```

Спасибо за баг репорт. Я понимаю от куда ноги растут у проблемы, но пока не знаю как решить. Буду думать и искать.

**Comment by Navatusein** [comment]
> Привет.
> 
> Нашел такую проблему. Склонение чисел не всегда согласуется со следующими после них существительными.
> 
> ```
> 1 <d>минута</d>      один минута
> 2 <d>минута</d>      два минута
> 3 <d>минута</d>      три минуты
> 41 <d>минута</d>    сорок один минута
> 44 <d>минута</d>    сорок четыре минуты
> ```

Я нашёл изящное решения проблемы.

**Comment by ein-erin** [comment]
> Я нашёл изящное решения проблемы.

Очень радует, что не придется делать склонения чисел на стороне HA и node red. Можно просто отправлять на озвучку показания как есть и не париться. Спасибо.
