### ISSUE TITLE
SAMPLE_RATE: 16000

### ISSUE THREAD

**Issue by Omirax** [Navatusein/Silero-TTS-Service#6]
Здравствуйте!

>Частота дискретизации SAMPLE_RATE:
SAMPLE_RATE: 48000 
Возможние значения: 48000, 24000, 8000
По умолчанию: 48000

Добавьте, пожалуйста, значение в 16000. 
Все ESP satellite rhasspy юзают как раз 16000.

**Comment by Navatusein** [comment]
> Здравствуйте!
> 
> >Частота дискретизации SAMPLE_RATE:
> SAMPLE_RATE: 48000 
> Возможние значения: 48000, 24000, 8000
> По умолчанию: 48000
> 
> Добавьте, пожалуйста, значение в 16000. 
> Все ESP satellite rhasspy юзают как раз 16000. 

К сожалению это невозможно. Модели Silero поддерживают только 8000, 24000, 48000. Другие значения не возможны.
